name: aliplayer_widget
description: >-
  A powerful and flexible vod component for Flutter applications.
  It integrates with flutter_aliplayer to provide high-quality video playback,
  seamless streaming, and a rich set of features for both live and on-demand video content.
  Whether you are building a video playback solution for education, entertainment,
  or any other application, it makes it easy to deliver an engaging video experience.

# NOTE: Please synchronize and modify the version number here:
# static const String _kWidgetVersion = 'x.y.z';
version: 7.0.0
homepage: https://www.aliyun.com/product/vod
topics:
  - player
  - video
  - video-player
  - aliyun

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the flutter aliplayer package
  flutter_aliplayer: ^7.0.0
#  flutter_aliplayer:
#    path: ../../flutter_sdk/flutter_aliplayer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
